# Site settings
title: Jen Chen Blog
email: 2692418611@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Blog!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  github201407

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
